// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apache/rocketmq/v1/admin.proto

package apache_rocketmq_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChangeLogLevelRequest_Level int32

const (
	ChangeLogLevelRequest_TRACE ChangeLogLevelRequest_Level = 0
	ChangeLogLevelRequest_DEBUG ChangeLogLevelRequest_Level = 1
	ChangeLogLevelRequest_INFO  ChangeLogLevelRequest_Level = 2
	ChangeLogLevelRequest_WARN  ChangeLogLevelRequest_Level = 3
	ChangeLogLevelRequest_ERROR ChangeLogLevelRequest_Level = 4
)

var ChangeLogLevelRequest_Level_name = map[int32]string{
	0: "TRACE",
	1: "DEBUG",
	2: "INFO",
	3: "WARN",
	4: "ERROR",
}

var ChangeLogLevelRequest_Level_value = map[string]int32{
	"TRACE": 0,
	"DEBUG": 1,
	"INFO":  2,
	"WARN":  3,
	"ERROR": 4,
}

func (x ChangeLogLevelRequest_Level) String() string {
	return proto.EnumName(ChangeLogLevelRequest_Level_name, int32(x))
}

func (ChangeLogLevelRequest_Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_754a6e0557016a5b, []int{0, 0}
}

type ChangeLogLevelRequest struct {
	Level                ChangeLogLevelRequest_Level `protobuf:"varint,1,opt,name=level,proto3,enum=apache.rocketmq.v1.ChangeLogLevelRequest_Level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ChangeLogLevelRequest) Reset()         { *m = ChangeLogLevelRequest{} }
func (m *ChangeLogLevelRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeLogLevelRequest) ProtoMessage()    {}
func (*ChangeLogLevelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_754a6e0557016a5b, []int{0}
}

func (m *ChangeLogLevelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeLogLevelRequest.Unmarshal(m, b)
}
func (m *ChangeLogLevelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeLogLevelRequest.Marshal(b, m, deterministic)
}
func (m *ChangeLogLevelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeLogLevelRequest.Merge(m, src)
}
func (m *ChangeLogLevelRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeLogLevelRequest.Size(m)
}
func (m *ChangeLogLevelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeLogLevelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeLogLevelRequest proto.InternalMessageInfo

func (m *ChangeLogLevelRequest) GetLevel() ChangeLogLevelRequest_Level {
	if m != nil {
		return m.Level
	}
	return ChangeLogLevelRequest_TRACE
}

type ChangeLogLevelResponse struct {
	Remark               string   `protobuf:"bytes,1,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeLogLevelResponse) Reset()         { *m = ChangeLogLevelResponse{} }
func (m *ChangeLogLevelResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeLogLevelResponse) ProtoMessage()    {}
func (*ChangeLogLevelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_754a6e0557016a5b, []int{1}
}

func (m *ChangeLogLevelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeLogLevelResponse.Unmarshal(m, b)
}
func (m *ChangeLogLevelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeLogLevelResponse.Marshal(b, m, deterministic)
}
func (m *ChangeLogLevelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeLogLevelResponse.Merge(m, src)
}
func (m *ChangeLogLevelResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeLogLevelResponse.Size(m)
}
func (m *ChangeLogLevelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeLogLevelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeLogLevelResponse proto.InternalMessageInfo

func (m *ChangeLogLevelResponse) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func init() {
	proto.RegisterEnum("apache.rocketmq.v1.ChangeLogLevelRequest_Level", ChangeLogLevelRequest_Level_name, ChangeLogLevelRequest_Level_value)
	proto.RegisterType((*ChangeLogLevelRequest)(nil), "apache.rocketmq.v1.ChangeLogLevelRequest")
	proto.RegisterType((*ChangeLogLevelResponse)(nil), "apache.rocketmq.v1.ChangeLogLevelResponse")
}

func init() { proto.RegisterFile("apache/rocketmq/v1/admin.proto", fileDescriptor_754a6e0557016a5b) }

var fileDescriptor_754a6e0557016a5b = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2c, 0x48, 0x4c,
	0xce, 0x48, 0xd5, 0x2f, 0xca, 0x4f, 0xce, 0x4e, 0x2d, 0xc9, 0x2d, 0xd4, 0x2f, 0x33, 0xd4, 0x4f,
	0x4c, 0xc9, 0xcd, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x82, 0xc8, 0xeb, 0xc1,
	0xe4, 0xf5, 0xca, 0x0c, 0x95, 0xe6, 0x30, 0x72, 0x89, 0x3a, 0x67, 0x24, 0xe6, 0xa5, 0xa7, 0xfa,
	0xe4, 0xa7, 0xfb, 0xa4, 0x96, 0xa5, 0xe6, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xb9,
	0x72, 0xb1, 0xe6, 0x80, 0xf8, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0xfa, 0x7a, 0x98, 0xba,
	0xf5, 0xb0, 0xea, 0xd4, 0x83, 0x70, 0x20, 0xba, 0x95, 0x6c, 0xb8, 0x58, 0xc1, 0x7c, 0x21, 0x4e,
	0x2e, 0xd6, 0x90, 0x20, 0x47, 0x67, 0x57, 0x01, 0x06, 0x10, 0xd3, 0xc5, 0xd5, 0x29, 0xd4, 0x5d,
	0x80, 0x51, 0x88, 0x83, 0x8b, 0xc5, 0xd3, 0xcf, 0xcd, 0x5f, 0x80, 0x09, 0xc4, 0x0a, 0x77, 0x0c,
	0xf2, 0x13, 0x60, 0x06, 0x49, 0xbb, 0x06, 0x05, 0xf9, 0x07, 0x09, 0xb0, 0x28, 0x19, 0x70, 0x89,
	0xa1, 0xdb, 0x51, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc6, 0xc5, 0x56, 0x94, 0x9a, 0x9b,
	0x58, 0x94, 0x0d, 0x76, 0x1f, 0x67, 0x10, 0x94, 0x67, 0x54, 0xc4, 0xc5, 0xea, 0x08, 0xf2, 0xb3,
	0x50, 0x26, 0x17, 0x1f, 0xaa, 0x56, 0x21, 0x4d, 0xa2, 0xbd, 0x20, 0xa5, 0x45, 0x8c, 0x52, 0x88,
	0x4b, 0x94, 0x18, 0x9c, 0x34, 0xb8, 0xb0, 0x04, 0xad, 0x13, 0xbb, 0x6f, 0x20, 0xd8, 0x25, 0x01,
	0x8c, 0x0b, 0x18, 0x19, 0x6f, 0x30, 0x32, 0xfe, 0x60, 0x64, 0x4c, 0x62, 0x03, 0xc7, 0x84, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x24, 0x51, 0x46, 0xe5, 0xab, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminClient interface {
	ChangeLogLevel(ctx context.Context, in *ChangeLogLevelRequest, opts ...grpc.CallOption) (*ChangeLogLevelResponse, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) ChangeLogLevel(ctx context.Context, in *ChangeLogLevelRequest, opts ...grpc.CallOption) (*ChangeLogLevelResponse, error) {
	out := new(ChangeLogLevelResponse)
	err := c.cc.Invoke(ctx, "/apache.rocketmq.v1.Admin/ChangeLogLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
type AdminServer interface {
	ChangeLogLevel(context.Context, *ChangeLogLevelRequest) (*ChangeLogLevelResponse, error)
}

// UnimplementedAdminServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (*UnimplementedAdminServer) ChangeLogLevel(ctx context.Context, req *ChangeLogLevelRequest) (*ChangeLogLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeLogLevel not implemented")
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_ChangeLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ChangeLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apache.rocketmq.v1.Admin/ChangeLogLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ChangeLogLevel(ctx, req.(*ChangeLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apache.rocketmq.v1.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeLogLevel",
			Handler:    _Admin_ChangeLogLevel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apache/rocketmq/v1/admin.proto",
}
